services:
  app:
    build: .
    ports:
      - "8091:8091"
    environment:
      spring.data.mongodb.uri:      mongodb://root:example@mongo:27017/communitiesDb?authSource=admin
      spring.data.mongodb.database: communitiesDb
      SPRING_RABBITMQ_HOST:         rabbitmq
      SPRING_RABBITMQ_PORT:         5672
      SPRING_RABBITMQ_USERNAME:     guest
      SPRING_RABBITMQ_PASSWORD:     guest
    depends_on:
      - mongo
      - rabbitmq
      - mongo-express

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE:       communitiesDb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL:           mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH:             false
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest