apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
        - name: community-service
          image: redditclone/communities-service:latest
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "communitiesDb"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: THREAD_SERVICE_URL
              value: "http://threads-service:8090/threads"
          envFrom:
            - secretRef:
                name: community-secrets

