apiVersion: v1
kind: Service
metadata:
  name: mongo-community
spec:
  clusterIP: None          
  selector:
    app: mongo-community
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
