apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_USER_DB: "user_service"
  POSTGRES_MODERATOR_DB: "moderator_service"
