apiVersion: v1
kind: Service
metadata:
  name: redisinsight
spec:
  type: NodePort
  selector:
    app: redisinsight
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001 # Access via http://localhost:30001