apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-notification
spec:
  serviceName: mongo-notification
  replicas: 1
  selector:
    matchLabels:
      app: mongo-notification
  template:
    metadata:
      labels:
        app: mongo-notification
    spec:
      containers:
        - name: mongo
          image: mongo:latest        
          ports:
            - name: mongo
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
