apiVersion: v1
kind: Service
metadata:
  name: mongo-notification
spec:
  clusterIP: None          
  selector:
    app: mongo-notification
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
