apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://root:example@mongo-notification:27017/notification_service_mongo?authSource=admin"
