apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby1ub3RpZmljYXRpb246MjcwMTcvbm90aWZpY2F0aW9uX3NlcnZpY2VfbW9uZ28/YXV0aFNvdXJjZT1hZG1pbg==
  SENDGRID_API_KEY: U0cuNlRGTklDcm9SSU80QVZCZWg3aTJPUS5pQkRhWU92ZEJBQXhBZkJGaTEyNURiRXBfME9hdXFEN3dQNWc4STkwdzRJ
