apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-moderator
spec:
  serviceName: "postgres-moderator"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-moderator
  template:
    metadata:
      labels:
        app: postgres-moderator
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_MODERATOR_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-moderator-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-moderator-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ] # only one Pod (one node) can mount this volume as read/write at a time,” which is perfect for a single-instance database.
        resources:
          requests:
            storage: 1Gi # This is how much disk space you’re asking for. The underlying storage class will provision a volume of at least this size
