spring:
  profiles:
      active: dev
  application:
    name: user-service
  config:
    import: optional:dev.yml

# Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 1234

# ORM configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

# mail configuration
  mail:
    host:  ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: ${MAIL_TEST_CONNECTION}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      "mail.smtp.starttls.required": true
      "mail.smtp.socketFactory.class": javax.net.ssl.SSLSocketFactory
      "mail.debug": true
server:
  error:
    include-message: always
  port: 8080

service_url: "http://localhost:${server.port}"

jwt:
  secret: ${JWT_SECRET}
  expirationms: 60000 # 1 minute
  refresh-token:
    secret: ${JWT_REFRESH_SECRET}
    expirationms: 600000 # 10 minutes

