name: Docker Build & Push

on:
  workflow_call:
    inputs:
      # Name of the artifact that CI uploaded (e.g. "packaged-artifact")
      artifact-name:
        required: true
        type: string

jobs:
  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: target/

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & tag Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest .
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:${{ github.sha }}

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:${{ github.sha }}
