name: Java CI with Maven

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      service-dir:
        required: true
        type: string

jobs:
  compile:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Compile
        run: mvn --batch-mode clean compile
        working-directory: ${{ inputs.service-dir }}

  test:
    name: Run Tests & Verify
    runs-on: ubuntu-latest
    needs: compile

    # Activate the 'test' profile so application-test.yml (with H2) is used
    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: mvn --batch-mode test
        working-directory: ${{ inputs.service-dir }}

      - name: Verify (integration, snapshot checks)
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ${{ inputs.service-dir }}

  build-artifact:
    name: Package Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Package JAR (skip tests)
        run: mvn --batch-mode clean package -DskipTests
        working-directory: ${{ inputs.service-dir }}

      - name: Upload artifact for downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact
          path: ${{ inputs.service-dir }}/target/*.jar
