name: Java CI with Maven

on:
  workflow_call:
    inputs:
      # The branch ref (e.g. refs/heads/main) that callers pass in
      branch:
        required: true
        type: string

jobs:
  compile:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Compile
        run: mvn --batch-mode clean compile

  test:
    name: Run Tests & Verify
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: mvn --batch-mode test

      - name: Verify (integration, snapshot checks)
        run: mvn --batch-mode --update-snapshots verify

  build-artifact:
    name: Package Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Package JAR (skip tests)
        run: mvn --batch-mode clean package -DskipTests

      - name: Upload artifact for downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact
          path: target/*.jar

