name: user-service CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - 'user-service/**'
  pull_request:
    # Only fire when the *destination* branch is one of these
    branches:
      - main
      - userservicebase
    paths:
      - 'user-service/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-java-maven.yml
    with:
      branch: ${{ github.ref }}
      service-dir: 'user-service'
    secrets: inherit

  docker:
    needs: ci
    uses: ./.github/workflows/cd-docker-push.yml
    with:
      artifact-name: 'packaged-artifact'
    secrets: inherit
