
server:
  port: 8090

user:
  service:
    url: http://localhost:8080

spring:
  application:
    name: ThreadService
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis_cache
      port: 6379
    mongodb:
      uri: mongodb://root:example@localhost:27017/threadDb?authSource=admin
      database: threadDb
  cache:
    type: redis

